### PR TITLE
Vk Support

### PR DESCRIPTION
**Pull request by ViktorSky**
Proxy support for -> SubClient.__init__
Proxy support for -> AsyncSubClient.__init__
Add 'get_vip_users' method

### CODE REVIEW

**Comment by Minori101** [comment]
LGTM. Sorry for such a long reply. I haven't visited the github for a long time because I gave up on amino

**Comment by ViktorSky** [comment]
U just change the `__init__.py` file xd

**Comment by Minori101** [comment]
> U just change the `__init__.py` file xd

No, i merged your commit and changed version in init.py. You can look at history in the sub_client.py

**Comment by ViktorSky** [comment]
okey

**Pull request merged**
